### ISSUE TITLE
Undersøg cafeencam og nedboer

### ISSUE THREAD

**Issue by Lukires** [datalogisk-kantineforening/infoscreen#81]
Hverken cafeencam eller nedboer virker på skærmen. De virker begge på min maskine, så har ikke kunne genskabe fejlen. De begge har det tilfælles, at de begge tilgår en .php side for at få billederne.

Har svært med at finde ud af hvorfor det ikke virker. Er .php blokeret på skærmen? Er der noget software på skærmen som ikke er opdateret? Eller noget helt tredje?

Hvis nogen har idéer vil jeg meget gerne høre dem :smile:

**Comment by BeneCollyridam** [comment]
Det er nok bare fordi WiFi forbindelsen ikke er konsistent på Raspberry
Pien.

**Comment by Lukires** [comment]
Jeg har aldrig set hverken af dem virke, mens andre ting, f.eks. crypt2 og quiz virker hver gang. De bruger dog heller ikke billeder, så det kan have noget med det at gøre I guess
